const wordList = [
    { word: "Cabeza", hint: "Parte del cuerpo" },
  { word: "Perro", hint: "Animal doméstico" },
  { word: "Libro", hint: "Objeto para leer" },
  { word: "Sol", hint: "Estrella que ilumina la Tierra" },
  { word: "Casa", hint: "Lugar donde vives" },
  { word: "Árbol", hint: "Planta con tronco y ramas" },
  { word: "Coche", hint: "Medio de transporte" },
  { word: "Playa", hint: "Lugar de arena y mar" },
  { word: "Gato", hint: "Animal doméstico" },
  { word: "Lápiz", hint: "Instrumento de escritura" },
  { word: "Manzana", hint: "Fruta roja" },
  { word: "Montaña", hint: "Elevación natural del terreno" },
  { word: "Agua", hint: "Líquido vital" },
  { word: "Ojo", hint: "Órgano de la visión" },
  { word: "Mesa", hint: "Superficie plana para poner cosas" },
  { word: "Luna", hint: "Satélite natural de la Tierra" },
  { word: "Flor", hint: "Parte reproductiva de una planta" },
  { word: "Amor", hint: "Sentimiento profundo" },
  { word: "Tiempo", hint: "Medida de la duración" },
  { word: "Familia", hint: "Grupo de personas relacionadas" },
  { word: "Amigo", hint: "Persona cercana" },
  { word: "Feliz", hint: "Sentimiento de alegría" },
  { word: "Cielo", hint: "Espacio sobre la Tierra" },
  { word: "Comida", hint: "Alimento" },
  { word: "Juego", hint: "Actividad de entretenimiento" },
  { word: "Música", hint: "Arte de los sonidos" },
  { word: "Sueño", hint: "Estado de descanso" },
  { word: "Risa", hint: "Expresión de alegría" },
  { word: "Viaje", hint: "Desplazamiento a otro lugar" },
  { word: "Color", hint: "Propiedad de los objetos" }
]